### ISSUE TITLE
Clase tablero y estado de juego

### ISSUE THREAD

**Issue by leonormurphy** [UNIZAR-30226-2023-05/Backend#34]

**Comment by IkerKa** [comment]
Propongo mejorar lo siguiente: 
El método `execute` devuelve un array con tres valores, lo cual impide la legibilidad del código. 
```js
//Comprobar estado de la nueva celda --> tablero.execute(nuevaCelda)
      let estadoCelda = this.tablero.execute(nuevaCelda);

      //estadoCelda => [proximaCleda (si es especial), tiraOtraVez, penalizacion]
      let proximaCelda = estadoCelda[0];
      let tiraOtraVez = estadoCelda[1];
      let penalizacion = estadoCelda[2];
```
Propongo que la función `execute` devuelva un objeto para que el resultado en su tratamiento sea el siguiente:
```js
let { nueva, turno, penalizacion } = this.tablero.execute(nuevaCelda)
```
Para ello, solamente es cambiar una del método `execute` de la clase celda.

**Comment by berrujaime** [comment]
¿Simplemente sería que el return del execute de la clase celda fuese:
```
return {this.nueva, this.turno, this.turnosperdidos}
```
en vez de:
```
return [this.nueva, this.turno, this.turnosperdidos]
```
?

Me parece bien el cambio ya que es mucho más visual y corto pero no estoy seguro si sólo sería cambiar eso. @IkerKa

**Comment by IkerKa** [comment]
Sii, pero tienes que poner el nombre en el return y todo perfe:
```js
return { nueva: this.nueva ... }
```
U otra manera es definir el objeto antes y luego devolverlo, como quieras @berrujaime

**Comment by berrujaime** [comment]
Ya está cambiado. Ya puedes coger los datos con la siguiente instrucción:
```let { nueva, turno, penalizacion } = this.tablero.execute(nuevaCelda)```
